"""
ppt_exporter.py  —  app/services/ppt_exporter.py

Produces a properly formatted 16:9 PPTX with:
  - Dedicated title slide
  - Per-slide stock images (optional, via Unsplash)
  - Consistent typography hierarchy per theme
  - Proper spacing and padding
  - No more single-layout-for-everything
"""

import os
import requests
from io import BytesIO
from typing import Optional

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.oxml.ns import qn
from lxml import etree

from app.services.theme_service import get_theme
from app.services.image_service import fetch_image_url

# 16:9 widescreen
SLIDE_WIDTH = Inches(13.33)
SLIDE_HEIGHT = Inches(7.5)


# ---------------------------------------------------------------------------
# Low-level helpers
# ---------------------------------------------------------------------------


def _rgb(hex_or_rgb):
    """Accept RGBColor passthrough."""
    return hex_or_rgb


def _set_slide_background(slide, color: RGBColor):
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_textbox(
    slide,
    left,
    top,
    width,
    height,
    text,
    font_name,
    font_size,
    color: RGBColor,
    bold=False,
    align=PP_ALIGN.LEFT,
    line_spacing=None,
):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.name = font_name
    run.font.size = font_size
    run.font.color.rgb = color
    run.font.bold = bold
    if line_spacing:
        p.line_spacing = line_spacing
    return txBox


def _add_image_from_url(slide, url: str, left, top, width, height):
    """Download image bytes and embed into slide."""
    try:
        resp = requests.get(url, timeout=8)
        resp.raise_for_status()
        image_stream = BytesIO(resp.content)
        slide.shapes.add_picture(image_stream, left, top, width, height)
        return True
    except Exception:
        return False


def _accent_bar(slide, color: RGBColor, top=Inches(0), width=None, height=Inches(0.07)):
    """Thin horizontal accent bar — used as a design element."""
    w = width or SLIDE_WIDTH
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        0,
        top,
        w,
        height,
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()  # no border


# ---------------------------------------------------------------------------
# Slide builders
# ---------------------------------------------------------------------------


def _build_title_slide(prs: Presentation, topic: str, theme: dict):
    """First slide — large centered title, no bullets."""
    slide_layout = prs.slide_layouts[6]  # blank layout
    slide = prs.slides.add_slide(slide_layout)
    _set_slide_background(slide, theme["bg"])

    # Accent bar at top
    _accent_bar(slide, theme["accent"], top=Inches(0), height=Inches(0.12))

    # Centered title
    _add_textbox(
        slide,
        left=Inches(1.2),
        top=Inches(2.2),
        width=Inches(10.9),
        height=Inches(2.5),
        text=topic,
        font_name=theme["title_font"],
        font_size=Pt(54),
        color=theme["title_color"],
        bold=True,
        align=PP_ALIGN.CENTER,
    )

    # Subtitle label
    _add_textbox(
        slide,
        left=Inches(1.2),
        top=Inches(5.0),
        width=Inches(10.9),
        height=Inches(0.6),
        text="Generated by DECKforge",
        font_name=theme["body_font"],
        font_size=Pt(14),
        color=theme["bullet_color"],
        align=PP_ALIGN.CENTER,
    )

    # Accent bar at bottom
    _accent_bar(
        slide, theme["accent"], top=SLIDE_HEIGHT - Inches(0.12), height=Inches(0.12)
    )

    return slide


def _build_content_slide(
    prs: Presentation,
    slide_data,
    theme: dict,
    index: int,
    image_url: Optional[str] = None,
):
    """Standard content slide — title + bullets, optional image on right."""
    slide_layout = prs.slide_layouts[6]  # blank
    slide = prs.slides.add_slide(slide_layout)
    _set_slide_background(slide, theme["bg"])

    has_image = image_url is not None

    # Layout columns
    title_left = Inches(0.5)
    title_top = Inches(0.4)
    title_width = Inches(8.5) if has_image else Inches(12.3)
    title_height = Inches(1.0)

    content_left = Inches(0.5)
    content_top = Inches(1.6)
    content_width = Inches(8.0) if has_image else Inches(12.3)
    content_height = Inches(5.5)

    # Slide number — top right
    _add_textbox(
        slide,
        left=Inches(12.0),
        top=Inches(0.3),
        width=Inches(1.0),
        height=Inches(0.5),
        text=str(index).zfill(2),
        font_name=theme["body_font"],
        font_size=Pt(11),
        color=theme["bullet_color"],
        align=PP_ALIGN.RIGHT,
    )

    # Accent bar left edge
    bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(0.08), SLIDE_HEIGHT)
    bar.fill.solid()
    bar.fill.fore_color.rgb = theme["accent"]
    bar.line.fill.background()

    # Title
    _add_textbox(
        slide,
        left=title_left + Inches(0.15),
        top=title_top,
        width=title_width,
        height=title_height,
        text=slide_data.title,
        font_name=theme["title_font"],
        font_size=theme["title_size"],
        color=theme["title_color"],
        bold=True,
    )

    # Divider line under title
    line = slide.shapes.add_shape(
        1,
        title_left + Inches(0.15),
        Inches(1.45),
        title_width,
        Inches(0.025),
    )
    line.fill.solid()
    line.fill.fore_color.rgb = theme["accent"]
    line.line.fill.background()

    # Bullets
    txBox = slide.shapes.add_textbox(
        content_left + Inches(0.15),
        content_top,
        content_width,
        content_height,
    )
    tf = txBox.text_frame
    tf.word_wrap = True

    for i, bullet in enumerate(slide_data.bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_before = Pt(6)
        p.space_after = Pt(4)

        # Bullet dot run
        dot_run = p.add_run()
        dot_run.text = "● "
        dot_run.font.name = theme["body_font"]
        dot_run.font.size = Pt(10)
        dot_run.font.color.rgb = theme["accent"]

        # Text run
        text_run = p.add_run()
        text_run.text = bullet
        text_run.font.name = theme["body_font"]
        text_run.font.size = theme["body_size"]
        text_run.font.color.rgb = theme["bullet_color"]

    # Image on right half
    if has_image:
        _add_image_from_url(
            slide,
            image_url,
            left=Inches(8.9),
            top=Inches(1.2),
            width=Inches(4.0),
            height=Inches(5.5),
        )

    return slide


# ---------------------------------------------------------------------------
# Main export function
# ---------------------------------------------------------------------------


def export_ppt(
    slides, filename: str, theme_name: str = "corporate", use_images: bool = True
) -> str:
    theme = get_theme(theme_name)

    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    # 1. Title slide
    _build_title_slide(prs, slides[0].title if slides else "Presentation", theme)

    # 2. Fetch images for all slides in one pass (skips if no API key)
    image_urls = [None] * len(slides)
    if use_images:
        for i, slide_data in enumerate(slides):
            image_urls[i] = fetch_image_url(slide_data.title)

    # 3. Content slides
    for i, (slide_data, img_url) in enumerate(zip(slides, image_urls), start=1):
        _build_content_slide(prs, slide_data, theme, index=i, image_url=img_url)

    os.makedirs("outputs", exist_ok=True)
    file_path = os.path.join("outputs", filename)
    prs.save(file_path)
    return file_path
